/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.ulpgc.dis.practica5;


import java.awt.Dimension;
import javax.swing.JOptionPane;


/**
 *
 * @author Andres
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        
        lienzo1.changeCoordinates(Lienzo.horizontalImagen() - Lienzo.horizontal(), 0);
        lienzo1.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Corners = new javax.swing.ButtonGroup();
        checkBoxPanel = new javax.swing.JPanel();
        allCheckBox = new javax.swing.JCheckBox();
        redCheckBox = new javax.swing.JCheckBox();
        greenCheckBox = new javax.swing.JCheckBox();
        blueCheckBox = new javax.swing.JCheckBox();
        errorLabel = new javax.swing.JLabel();
        radioButtonPanel = new javax.swing.JPanel();
        upperLeft = new javax.swing.JRadioButton();
        upperRight = new javax.swing.JRadioButton();
        downLeft = new javax.swing.JRadioButton();
        downRight = new javax.swing.JRadioButton();
        urlPanel = new javax.swing.JPanel();
        imagenLabel = new javax.swing.JLabel();
        urlTextfield = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lienzo1 = new es.ulpgc.dis.practica5.Lienzo();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Image Loader");

        checkBoxPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Color Filter"));

        allCheckBox.setSelected(true);
        allCheckBox.setText("All Colors");
        allCheckBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                allCheckBoxItemStateChanged(evt);
            }
        });
        allCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allCheckBoxActionPerformed(evt);
            }
        });

        redCheckBox.setSelected(true);
        redCheckBox.setText("Red");
        redCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redCheckBoxActionPerformed(evt);
            }
        });

        greenCheckBox.setSelected(true);
        greenCheckBox.setText("Green");
        greenCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greenCheckBoxActionPerformed(evt);
            }
        });

        blueCheckBox.setSelected(true);
        blueCheckBox.setText("Blue");
        blueCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueCheckBoxActionPerformed(evt);
            }
        });

        errorLabel.setForeground(new java.awt.Color(255, 0, 51));
        errorLabel.setText("At least one color ");
        errorLabel.setEnabled(true);
        errorLabel.setVisible(false);

        javax.swing.GroupLayout checkBoxPanelLayout = new javax.swing.GroupLayout(checkBoxPanel);
        checkBoxPanel.setLayout(checkBoxPanelLayout);
        checkBoxPanelLayout.setHorizontalGroup(
            checkBoxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkBoxPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(checkBoxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(allCheckBox)
                    .addComponent(greenCheckBox)
                    .addComponent(redCheckBox)
                    .addComponent(blueCheckBox))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(checkBoxPanelLayout.createSequentialGroup()
                .addComponent(errorLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        checkBoxPanelLayout.setVerticalGroup(
            checkBoxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkBoxPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(allCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(redCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(greenCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(blueCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(errorLabel)
                .addContainerGap())
        );

        radioButtonPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Logo Position"));

        Corners.add(upperLeft);
        upperLeft.setText("upperLeft");
        upperLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upperLeftActionPerformed(evt);
            }
        });

        Corners.add(upperRight);
        upperRight.setText("upperRight");
        upperRight.setSelected(true);
        upperRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upperRightActionPerformed(evt);
            }
        });

        Corners.add(downLeft);
        downLeft.setText("downLeft");
        downLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downLeftActionPerformed(evt);
            }
        });

        Corners.add(downRight);
        downRight.setText("downRight");
        downRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downRightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout radioButtonPanelLayout = new javax.swing.GroupLayout(radioButtonPanel);
        radioButtonPanel.setLayout(radioButtonPanelLayout);
        radioButtonPanelLayout.setHorizontalGroup(
            radioButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(radioButtonPanelLayout.createSequentialGroup()
                .addGroup(radioButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(upperLeft)
                    .addComponent(upperRight)
                    .addComponent(downLeft)
                    .addComponent(downRight))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        radioButtonPanelLayout.setVerticalGroup(
            radioButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(radioButtonPanelLayout.createSequentialGroup()
                .addComponent(upperLeft)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(upperRight)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(downLeft)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(downRight))
        );

        urlPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("URL loader"));

        imagenLabel.setText("Image URL:");

        urlTextfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                urlTextfieldFocusGained(evt);
            }
        });
        urlTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urlTextfieldActionPerformed(evt);
            }
        });

        jButton1.setText("Load Image");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout urlPanelLayout = new javax.swing.GroupLayout(urlPanel);
        urlPanel.setLayout(urlPanelLayout);
        urlPanelLayout.setHorizontalGroup(
            urlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(urlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagenLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(urlTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        urlPanelLayout.setVerticalGroup(
            urlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(urlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(urlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imagenLabel)
                    .addComponent(urlTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout lienzo1Layout = new javax.swing.GroupLayout(lienzo1);
        lienzo1.setLayout(lienzo1Layout);
        lienzo1Layout.setHorizontalGroup(
            lienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        lienzo1Layout.setVerticalGroup(
            lienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(checkBoxPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(radioButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(urlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lienzo1, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkBoxPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(radioButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(urlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lienzo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void allCheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_allCheckBoxItemStateChanged
        // TODO add your handling code here:
        errorLabel.setVisible(false);
    }//GEN-LAST:event_allCheckBoxItemStateChanged

    private void redCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redCheckBoxActionPerformed
        // TODO add your handling code here:
        if (!blueCheckBox.isSelected() && !greenCheckBox.isSelected()) {
            //ERROR
            errorLabel.setVisible(true);
            redCheckBox.setSelected(true);
        } else {
            errorLabel.setVisible(false);
            Lienzo.setRed(redCheckBox.isSelected());

            if (!redCheckBox.isSelected()) {
                allCheckBox.setSelected(false);

            }
            lienzo1.repaint();
        }
    }//GEN-LAST:event_redCheckBoxActionPerformed

    private void greenCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenCheckBoxActionPerformed
        // TODO add your handling code here:
        if (!redCheckBox.isSelected() && !blueCheckBox.isSelected()) {
            //ERROR
            errorLabel.setVisible(true);
            greenCheckBox.setSelected(true);
        } else {
            errorLabel.setVisible(false);
            Lienzo.setGreen(greenCheckBox.isSelected());

            if (!greenCheckBox.isSelected()) {
                allCheckBox.setSelected(false);

            }
            lienzo1.repaint();
        }
    }//GEN-LAST:event_greenCheckBoxActionPerformed

    private void blueCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueCheckBoxActionPerformed
        // TODO add your handling code here:
        if (!redCheckBox.isSelected() && !greenCheckBox.isSelected()) {
            //ERROR
            errorLabel.setVisible(true);
            blueCheckBox.setSelected(true);
        } else {
            errorLabel.setVisible(false);
            Lienzo.setBlue(blueCheckBox.isSelected());

            if (!blueCheckBox.isSelected()) {
                allCheckBox.setSelected(false);

            }
            lienzo1.repaint();
        }
    }//GEN-LAST:event_blueCheckBoxActionPerformed

    private void allCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allCheckBoxActionPerformed
        if (allCheckBox.isSelected()) {
            blueCheckBox.setSelected(true);
            Lienzo.setBlue(blueCheckBox.isSelected());
            greenCheckBox.setSelected(true);
            Lienzo.setGreen(greenCheckBox.isSelected());
            redCheckBox.setSelected(true);
            Lienzo.setRed(redCheckBox.isSelected());
            lienzo1.repaint();
        }
    }//GEN-LAST:event_allCheckBoxActionPerformed

    private void upperLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upperLeftActionPerformed
        // TODO add your handling code here:
        lienzo1.setPreferredSize(new Dimension(Lienzo.horizontalImagen(), Lienzo.verticalImagen()));
        lienzo1.changeCoordinates(0, 0);
        lienzo1.repaint();
    }//GEN-LAST:event_upperLeftActionPerformed

    private void upperRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upperRightActionPerformed
        // TODO add your handling code here:
        lienzo1.setPreferredSize(new Dimension(Lienzo.horizontalImagen(), Lienzo.verticalImagen()));
        lienzo1.changeCoordinates(Lienzo.horizontalImagen() - Lienzo.horizontal(), 0);
        lienzo1.repaint();
    }//GEN-LAST:event_upperRightActionPerformed

    private void downLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downLeftActionPerformed
        // TODO add your handling code here:
        lienzo1.setPreferredSize(new Dimension(Lienzo.horizontalImagen(), Lienzo.verticalImagen()));
        lienzo1.changeCoordinates(0, Lienzo.verticalImagen() - Lienzo.vertical());
        lienzo1.repaint();
    }//GEN-LAST:event_downLeftActionPerformed

    private void downRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downRightActionPerformed
        // TODO add your handling code here:
        lienzo1.setPreferredSize(new Dimension(Lienzo.horizontalImagen(), Lienzo.verticalImagen()));
        lienzo1.changeCoordinates(Lienzo.horizontalImagen() - Lienzo.horizontal(), Lienzo.verticalImagen() - Lienzo.vertical());
        lienzo1.repaint();
    }//GEN-LAST:event_downRightActionPerformed

    private void urlTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urlTextfieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_urlTextfieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(urlTextfield.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "not valid URL", "Value not valid",
                    JOptionPane.ERROR_MESSAGE);
        }else{
            lienzo1.setUrlImage(urlTextfield.getText());
            lienzo1.repaint();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void urlTextfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_urlTextfieldFocusGained
        // TODO add your handling code here:
        urlTextfield.setText("");
        urlTextfield.paste();
    }//GEN-LAST:event_urlTextfieldFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Corners;
    private javax.swing.JCheckBox allCheckBox;
    private javax.swing.JCheckBox blueCheckBox;
    private javax.swing.JPanel checkBoxPanel;
    private javax.swing.JRadioButton downLeft;
    private javax.swing.JRadioButton downRight;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JCheckBox greenCheckBox;
    private javax.swing.JLabel imagenLabel;
    private javax.swing.JButton jButton1;
    private es.ulpgc.dis.practica5.Lienzo lienzo1;
    private javax.swing.JPanel radioButtonPanel;
    private javax.swing.JCheckBox redCheckBox;
    private javax.swing.JRadioButton upperLeft;
    private javax.swing.JRadioButton upperRight;
    private javax.swing.JPanel urlPanel;
    private javax.swing.JTextField urlTextfield;
    // End of variables declaration//GEN-END:variables
}
